name: Test

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  FORCE_COLOR: "1"

jobs:
  pytest:
    name: Pytest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
        - "3.10"
        - "3.11"
        - "3.12"
        - "3.13"
        - "3.14"
        - "3.15"
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - name: Install uv
      uses: astral-sh/setup-uv@eac588ad8def6316056a12d4907a9d4d84ff7a3b # v7.3.0
      with:
        python-version: ${{ matrix.python-version }}
        version: ">=0.9.0"
    - name: Install dependencies
      run: |
        uv sync
    - name: Run tests
      run: |
        uv run pytest

  types:
    name: Static Analysis
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - name: Install uv
      uses: astral-sh/setup-uv@eac588ad8def6316056a12d4907a9d4d84ff7a3b # v7.3.0
      with:
        version: ">=0.9.0"
    - name: Install dependencies
      run: |
        uv sync
    - name: Check types with mypy
      run: |
        uv run mypy cz_version_bump tests
    - name: Check types with ty
      run: |
        uv run ty check
