name: Test

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  FORCE_COLOR: "1"

jobs:
  build-package:
    name: Build & verify package
    runs-on: ubuntu-latest
    outputs:
      supported-python-versions: ${{ steps.baipp.outputs.supported_python_classifiers_json_array }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: hynek/build-and-inspect-python-package@2abe76da66d0a6a4a227101f9348ee855797cfa5 # v3.0.1
        id: baipp

  pytest:
    name: Pytest
    needs: [build-package]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ${{ fromJson(needs.build-package.outputs.supported-python-versions) }}
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false
    - name: Install uv
      uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
      with:
        python-version: ${{ matrix.python-version }}
        version: ">=0.12.0"
    - name: Install dependencies
      run: |
        uv sync
    - name: Run tests
      run: |
        uv run pytest

  types:
    name: Static Analysis
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false
    - name: Install uv
      uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
      with:
        version: ">=0.12.0"
    - name: Install dependencies
      run: |
        uv sync
    - name: Check types with mypy
      run: |
        uv run mypy cz_version_bump tests
    - name: Check types with ty
      run: |
        uv run ty check
